# Generated by Django 4.0.4 on 2022-07-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_favoritemusic'),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('genre', models.CharField(max_length=50)),
                ('duration_in_seconds', models.TimeField()),
                ('album', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Трек',
                'verbose_name_plural': 'Треки',
            },
        ),
        migrations.RemoveField(
            model_name='selection',
            name='fk',
        ),
        migrations.DeleteModel(
            name='Music',
        ),
        migrations.DeleteModel(
            name='Selection',
        ),
    ]
