# Generated by Django 4.0.4 on 2022-07-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_track_remove_selection_fk_delete_music_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='track',
            name='release_date',
            field=models.DateField(blank=True),
        ),
    ]
