# Generated by Django 4.0.4 on 2022-07-10 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0005_alter_track_duration_in_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='stared_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
