# Generated by Django 4.0.4 on 2022-07-10 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteMusic',
        ),
    ]
